spring:
  application:
    name: customers

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: customer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.shoplith.customers.events.CustomerProfileCreateEvent

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/shoplith_customers
    username: postgres
    password: vyrazu
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: ALWAYS
  devtools:
    restart:
      enabled: true
jwt:
  secret: dsamdnash32qw903u0riowqejoirj3290roijaskflnlksznfklnsanfasf

server:
  port: 8009