spring:
  application:
    name: customers
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/shoplith_customers
    username: postgres
    password: Souvikp683@
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: ALWAYS
  devtools:
    restart:
      enabled: true

server:
  port: 8001
